name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm run test:unit
    - run: npm run build
      env:
        CI: true

    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: dist

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: dist
